name: jlab_datascience
dependencies:
  - python=3.9
  - pip
  - pip:
    - matplotlib
    - numpy
    - pandas
    - scikit-learn
    - jupyter
    - bokeh
    - tensorflow
    - tf-models-official
    - scipy
    - mlflow
    - hyperopt
